window.APP_CONFIG = {
  projectName: {
    ko: "GATE",
    en: "GATE",
  },
  supabase: {
    url: "https://YOUR_PROJECT.supabase.co",
    anonKey: "YOUR_PUBLIC_ANON_KEY",
    table: "manifestos",
    bucket: "manifesto-images",
  },
  constraints: {
    bodyMinLength: 20,
    bodyMaxLength: 500,
    authorMaxLength: 40,
    maxTags: 3,
    maxImageBytes: 5 * 1024 * 1024,
    allowedImageTypes: ["image/jpeg", "image/png", "image/webp"],
  },
  tags: [
    { id: "labor", label: { ko: "노동", en: "Labor" } },
    { id: "care", label: { ko: "돌봄", en: "Care" } },
    { id: "housing", label: { ko: "주거", en: "Housing" } },
    { id: "climate", label: { ko: "기후", en: "Climate" } },
    { id: "technology", label: { ko: "기술", en: "Technology" } },
    { id: "education", label: { ko: "교육", en: "Education" } },
    { id: "city", label: { ko: "도시", en: "City" } },
    { id: "community", label: { ko: "커뮤니티", en: "Community" } },
  ],
  demoEntries: [
    {
      id: "demo-1",
      created_at: "2026-04-10T12:00:00.000Z",
      body: "우리는 돌봄이 개인의 희생이 아니라 모두의 기반이라는 사실을 다시 선언한다.",
      locale: "ko",
      author_name: null,
      is_anonymous: true,
      tags: ["care", "community"],
      image_url: null,
      status: "visible",
    },
    {
      id: "demo-2",
      created_at: "2026-04-09T08:30:00.000Z",
      body: "Housing is not a luxury object. It is the minimum architecture of dignity.",
      locale: "en",
      author_name: "Collective A",
      is_anonymous: false,
      tags: ["housing", "city"],
      image_url: null,
      status: "visible",
    },
  ],
  translations: {
    ko: {
      pageTitle: "GATE",
      brandName: "GATE",
      navAbout: "소개",
      navArchive: "아카이브",
      navSubmit: "참여",
      heroEyebrow: "Participatory Archive",
      heroTitle: "지금의 문장을 남기고 함께 미래를 선언합니다.",
      heroLead:
        "이곳은 짧고 강한 선언문들이 쌓이는 공개 아카이브입니다. 누구나 자신의 문장을 남길 수 있고, 등록된 글은 즉시 타임라인에 반영됩니다.",
      heroPrimaryCta: "선언문 남기기",
      heroSecondaryCta: "아카이브 보기",
      heroPanelLabel: "Archive Note",
      heroPanelStatement:
        "“아카이브는 과거를 보관하는 장소가 아니라, <em>다음 문장을 예고하는 장소</em>일 수 있다.”",
      heroFactImmediateLabel: "공개 방식",
      heroFactImmediateValue: "제출 직후 즉시 공개",
      heroFactModerationLabel: "운영 정책",
      heroFactModerationValue: "문제 있는 글은 이후 숨김 처리",
      heroFactFormatLabel: "형식",
      heroFactFormatValue: "짧은 선언문, 이름 또는 익명, 태그, 이미지 1장",
      guideKicker: "How It Works",
      guideTitle: "참여는 짧고, 기록은 오래 남습니다.",
      guideStep1Title: "문장을 고릅니다",
      guideStep1Body:
        "지금 가장 중요하다고 믿는 한 문장을 20자 이상 500자 이하로 적습니다.",
      guideStep2Title: "태그와 언어를 붙입니다",
      guideStep2Body:
        "언어와 주제를 표시하면 아카이브 안에서 다른 선언들과 함께 연결됩니다.",
      guideStep3Title: "즉시 타임라인에 남깁니다",
      guideStep3Body:
        "제출이 끝나면 새 카드가 바로 상단에 나타납니다. 운영자는 사후에만 숨김 처리합니다.",
      archiveKicker: "Archive",
      archiveTitle: "지금까지 도착한 선언문",
      archiveBody:
        "언어, 태그, 키워드로 아카이브를 탐색하세요. 모든 카드는 최신순으로 정렬됩니다.",
      archiveHint: "검색 대상은 본문과 작성자 이름입니다.",
      archivePageLink: "전체 선언문 한 번에 보기",
      archivePageTitle: "모든 선언문",
      archivePageLead:
        "지금까지 등록된 선언문을 최신순으로 한 번에 읽을 수 있는 페이지입니다.",
      archivePageBack: "메인으로 돌아가기",
      archivePageCount: "총 {count}개의 선언문",
      archivePageEmpty: "아직 공개된 선언문이 없습니다.",
      filterLocaleLabel: "언어 필터",
      filterTagLabel: "태그 필터",
      filterSearchLabel: "키워드 검색",
      filterSearchPlaceholder: "본문이나 작성자 이름을 검색하세요",
      filterAllLocales: "모든 언어",
      filterLocaleKo: "한국어",
      filterLocaleEn: "영어",
      filterAllTags: "모든 태그",
      archiveCount: "{count}개의 선언문",
      archiveLoading: "아카이브를 불러오는 중입니다.",
      archiveEmpty: "조건에 맞는 선언문이 아직 없습니다.",
      archiveSetupNotice:
        "Supabase 설정 전이라 데모 데이터가 보입니다. `config.js`에 프로젝트 URL과 anon key를 입력하면 실제 아카이브로 연결됩니다.",
      archiveError:
        "아카이브를 불러오지 못했습니다. Supabase 설정과 정책을 확인해 주세요.",
      submitKicker: "Contribute",
      submitTitle: "당신의 선언문을 남겨 주세요.",
      submitBody:
        "익명 또는 이름 표기를 선택할 수 있습니다. 이미지 첨부는 선택이며, 텍스트는 즉시 공개됩니다.",
      formBodyLabel: "선언문 본문",
      formBodyHint: "20자 이상 500자 이하로 입력하세요.",
      formLocaleLabel: "글의 언어",
      formAuthorLabel: "이름 또는 단체명",
      formAuthorHint: "비워두거나 익명을 선택하면 익명으로 표기됩니다.",
      formAnonymousLabel: "이 글을 익명으로 공개하기",
      formTagsLabel: "태그 선택",
      formTagsHint: "1개 이상 3개 이하로 선택하세요.",
      formImageLabel: "이미지 첨부",
      formImageHint: "JPG, PNG, WEBP 파일 1장만 업로드할 수 있습니다. 최대 5MB.",
      formSubmitButton: "즉시 게시",
      formSubmitting: "제출 중입니다...",
      formSuccess: "선언문이 등록되었습니다. 방금 아카이브 상단에 반영했어요.",
      formErrorGeneric: "제출에 실패했습니다. 잠시 뒤 다시 시도해 주세요.",
      formErrorBody:
        "선언문은 20자 이상 500자 이하로 입력해야 합니다.",
      formErrorTags: "태그는 1개 이상 3개 이하로 선택해야 합니다.",
      formErrorAuthor: "이름은 40자 이하로 입력해 주세요.",
      formErrorImageType: "이미지는 JPG, PNG, WEBP 형식만 허용됩니다.",
      formErrorImageSize: "이미지 파일은 5MB 이하만 업로드할 수 있습니다.",
      formErrorSpam: "제출이 차단되었습니다. 다시 시도해 주세요.",
      formImageSelected: "선택한 파일: {name}",
      authorAnonymous: "익명",
      footerCopy:
        "GitHub Pages와 Supabase로 운영되는 참여형 아카이브. 필요한 문구와 태그는 <code>config.js</code>에서 바로 바꿀 수 있습니다.",
    },
    en: {
      pageTitle: "GATE",
      brandName: "GATE",
      navAbout: "About",
      navArchive: "Archive",
      navSubmit: "Submit",
      heroEyebrow: "Participatory Archive",
      heroTitle: "Leave a sentence for the present and declare a shared future.",
      heroLead:
        "This is a public archive for short, sharp manifestos. Anyone can add a statement, and every approved submission appears in the timeline immediately.",
      heroPrimaryCta: "Add a Manifesto",
      heroSecondaryCta: "Browse Archive",
      heroPanelLabel: "Archive Note",
      heroPanelStatement:
        "“An archive does not only hold the past. It can also <em>announce the next sentence</em>.”",
      heroFactImmediateLabel: "Publishing",
      heroFactImmediateValue: "Visible immediately after submission",
      heroFactModerationLabel: "Moderation",
      heroFactModerationValue: "Problematic posts can be hidden later",
      heroFactFormatLabel: "Format",
      heroFactFormatValue: "Short statement, named or anonymous, tags, one image",
      guideKicker: "How It Works",
      guideTitle: "The contribution is short. The record stays.",
      guideStep1Title: "Write one sentence",
      guideStep1Body:
        "Submit a statement between 20 and 500 characters about what matters most right now.",
      guideStep2Title: "Add language and tags",
      guideStep2Body:
        "Language and topic tags help your text connect with other statements in the archive.",
      guideStep3Title: "See it appear instantly",
      guideStep3Body:
        "After submission, the new card appears at the top of the timeline right away.",
      archiveKicker: "Archive",
      archiveTitle: "Statements received so far",
      archiveBody:
        "Browse the archive by language, tag, or keyword. Every card is sorted from newest to oldest.",
      archiveHint: "Search looks through statement text and author name.",
      archivePageLink: "View all statements at once",
      archivePageTitle: "All Statements",
      archivePageLead:
        "A dedicated page where every published statement appears in one continuous list.",
      archivePageBack: "Back to main page",
      archivePageCount: "{count} statements total",
      archivePageEmpty: "There are no public statements yet.",
      filterLocaleLabel: "Language",
      filterTagLabel: "Tag",
      filterSearchLabel: "Keyword search",
      filterSearchPlaceholder: "Search text or author name",
      filterAllLocales: "All languages",
      filterLocaleKo: "Korean",
      filterLocaleEn: "English",
      filterAllTags: "All tags",
      archiveCount: "{count} statements",
      archiveLoading: "Loading the archive.",
      archiveEmpty: "No statements match the current filters yet.",
      archiveSetupNotice:
        "Supabase is not configured yet, so you are seeing demo content. Add your project URL and anon key to `config.js` to connect the live archive.",
      archiveError:
        "The archive could not be loaded. Please check your Supabase settings and policies.",
      submitKicker: "Contribute",
      submitTitle: "Leave your manifesto.",
      submitBody:
        "You can publish with your name or anonymously. Image upload is optional, and text appears immediately.",
      formBodyLabel: "Manifesto text",
      formBodyHint: "Write between 20 and 500 characters.",
      formLocaleLabel: "Statement language",
      formAuthorLabel: "Name or collective",
      formAuthorHint: "Leave blank or choose anonymity to display as Anonymous.",
      formAnonymousLabel: "Publish this statement anonymously",
      formTagsLabel: "Choose tags",
      formTagsHint: "Select between 1 and 3 tags.",
      formImageLabel: "Attach an image",
      formImageHint: "Upload one JPG, PNG, or WEBP image up to 5MB.",
      formSubmitButton: "Publish Now",
      formSubmitting: "Publishing...",
      formSuccess: "Your manifesto is live. It has been added to the top of the archive.",
      formErrorGeneric: "Submission failed. Please try again in a moment.",
      formErrorBody:
        "The statement must be between 20 and 500 characters long.",
      formErrorTags: "Please choose between 1 and 3 tags.",
      formErrorAuthor: "Author name must be 40 characters or fewer.",
      formErrorImageType: "Only JPG, PNG, and WEBP images are allowed.",
      formErrorImageSize: "Images must be 5MB or smaller.",
      formErrorSpam: "Submission was blocked. Please try again.",
      formImageSelected: "Selected file: {name}",
      authorAnonymous: "Anonymous",
      footerCopy:
        "A participatory archive powered by GitHub Pages and Supabase. You can update the copy and tags directly in <code>config.js</code>.",
    },
  },
};
